# see http://docs.travis-ci.com/user/languages/java/
language: java
jdk:
  - oraclejdk8

# see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# see http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2

after_success:
- mvn versioneye:update -DapiKey=$versioneye_api_key

# see http://docs.travis-ci.com/user/notifications/
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/afba008a6e2518c22d4c
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  slack:
    secure: hXv9JWC8PMP1ouQioNcmu0lNElNWXaFjqdDkytdpyJM/dMpTGLEtTzOqIVI/NmznHXRWZnLl4dhxAcPbn+ai8hC0EXI/M3CAcOrAfbnc/8hYIc3YhftXqmzlQMJjG0fdDl/G+DpSwN6Nz3hNnsfmOxuc6tpv39+wPt0mI1QMAtw=

# see https://docs.travis-ci.com/user/encryption-keys/
# see https://docs.travis-ci.com/user/environment-variables/
env:
  global:
    # exposes 'versioneye_api_key'
    secure: KCMtMzeBnSd5RqAQrHoO/DsDyATfGoupPS/u3hWX9plnCXnl/YtuJ+zJU0gj73h7Duv3r+qc/Az+W87Ebo6axwk/Ia8J7NT4gIoaAFg6sr+11ZZ+3WWrJrSg7ODkb87cQhS+gF6jRyQtVOXvkC+LE6NyuJFgwzLnyTECRzfjxgg=
